FROM aerogear/digger-android-builder

# install node 4.x
RUN curl --silent --location https://rpm.nodesource.com/setup_4.x | bash -
RUN yum -y install nodejs

# install Cordova CLI
RUN npm install -g cordova@6
